# Generated by Django 5.0.2 on 2025-05-20 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_category_type'),
        ('finance', '0002_default_categories'),
    ]

    operations = [
    ]
